### ISSUE TITLE
SDK Version?

### ISSUE THREAD

**Issue by njss** [axelpale/tet-node-client#1]
Hi,

This is a great contribution. 
Can you tell me in which version of the eyetribe sdk is this project relying on?
Is it finished?

Thank you!

best,
Nelson

**Comment by axelpale** [comment]
Hi, thanks for the question and sorry for the delay.

I cannot recall the sdk version but we used the tet-node-client project with the $99 Eye Tribe tracker. It was around the time when Pro tracker became available, if that helps.

The project was almost finished but cancelled due to change in our research focus. Calibration features are not completed for instance.

Seems that [TheEyeTribe is no more](https://www.pygaze.org/2016/12/the-eyetribe-stops-and-that-stinks/) so further development of the project seems unlikely.
